# These options apply to how the script will operate.
script_options:
  # Switch between testnet and mainnet
  # Setting this to False will use REAL funds, use at your own risk
  TEST_MODE: True
  LOG_TRADES: True
  #the MAIN_FILES_PATH will be the folder where the LOG_FILE, HISTORY_LOG_FILE, COIN_BOUGHT and BOT_STATS files will be stored. 
  #By default, if it is empty, these files will be housed in the main folder of the Bot. Not yet implemented
  MAIN_FILES_PATH: ""
  LOG_FILE: 'trades.html'
  HISTORY_LOG_FILE: 'history.html'
  COINS_BOUGHT: 'coins_bought.json'
  BOT_STATS: 'bot_stats.json'
  #This file will show the currencies contributed by the module or the compa modules for the bot
  EXTERNAL_COINS: 'excoin.txt'
  DEBUG: True
  
  #all binance requests from our bot will be proxied
  PROXY_HTTP: '' #'http://localhost:8090'
  PROXY_HTTPS: ''

  # Set this to true if you are accessing binance from within the United States of America
  # Need to change TLD
  AMERICAN_USER: False

# These options apply to the trading methods the script executes
trading_options:
 
  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDT #BTC

  # Total amount per trade (your base currency balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  # Binance uses a minimum of 10 USDT per trade, add a bit extra to enable selling if the price drops.
  # Recommended: no less than 12 USDT. Suggested: 15 or more.
  TRADE_TOTAL: 11 #0.00161373
  
  # Maximum number of trade 'slots' at any time (your USDT balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  TRADE_SLOTS: 8

  # EX_PAIRS is a list of fiat currencies and margin symbols that I am excluding.
  # Anything added here will be excluded from coin withdrawal and will not be sold.
  EX_PAIRS: ['PAX', 'EUR', 'GBP', 'JPY', 'USD', 'AUD', 'DOWN', 'UP', 'ONE', 'USDC', 'BNB', 'SHIB', 'VET', 'AXS', 'NEAR', 'GRT', 'SOL', 'CHR', 'BUSD']

  # the amount of time in MINUTES to calculate the difference from the current price (minimum: 1).
  TIME_DIFFERENCE: 1

  # Number of times to check for TP/SL during each TIME_DIFFERENCE (minimum: 1).
  # Don't spam the Binance API, you will be banned (max 1200 requests per minute per IP).
  RECHECK_INTERVAL: 15 #6

  # the difference in % between the first and second checks for the price. default 0.25
  CHANGE_IN_PRICE: 100 #0.25

  # define in % when to sell a coin that's not making a profit.
  STOP_LOSS: 100

  # define in % when to take profit on a profitable coin.
  TAKE_PROFIT: 0.15 #0.25

  # Use custom tickers.txt list for filtering pairs.
  # Name of custom tickers list
  CUSTOM_LIST: True
  TICKERS_LIST: 'tickers.txt'
   
  # whether to use trailing stop loss or not; default is True
  # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
  # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
  # NOTE -SELL_ON_SIGNAL_ONLY will override USE_TRAILING_STOP_LOSS
  USE_TRAILING_STOP_LOSS: False
  TRAILING_STOP_LOSS: .1
  TRAILING_TAKE_PROFIT: .2

  # Following are used to override SL, TP, TSL & TTP & SELL_ON_SIGNAL_ONLY in the case of a market crash
  # when hit SESSION_TAKE_PROFIT %, sell all coins and stop bot
  # when hit SESSION_STOP_LOSS %, sell all coins and stop bot.
  # Note, SESSION_STOP_LOSS needs to be a NEGATIVE number i.e. -2
  SESSION_TPSL_OVERRIDE: False
  SESSION_TAKE_PROFIT: 0.2
  SESSION_STOP_LOSS: -1

  # Let a signalling module control sell of coin
  # NOTE - If USE_TRAILING_STOP_LOSS: True then this needs to be False
  SELL_ON_SIGNAL_ONLY: False

  # Trading fee in % per trade.
  # If using 0.075% (using BNB for fees) you must have BNB in your account to cover trading fees.
  # If using BNB for fees, it MUST be enabled in your Binance 'Dashboard' page (checkbox).
  TRADING_FEE: 0.075
  #TRADING_FEE: 0.1
  
  #if it is activated, the commission is ignored in WIN = (SELL_PRICE + FEE) >= (BUY_PRICE + FEE)
  IGNORE_FEE: False
  
  # Discord integration
  # Used to push alerts, messages etc to a discord channel
  MSG_DISCORD: False
  
  #restart all modules every hour
  RESTART_MODULES: False
  
  #minimal mode set to 0, complete mode set to 1, termux mode set to 2
  SCREEN_MODE: 2
  STATIC_MAIN_INFO: False
  DISABLE_TIMESTAMPS: True  
  SHOW_INITIAL_CONFIG: False
  
  #If the sale time exceeds 6 hours it is automatically added to the black list of currencies. If set to 0 this can be disable
  MAX_HOLDING_TIME: 12
  
  SHOW_TABLE_COINS_BOUGHT: True  
  #Thanks to the idea of Norker Play, the table of purchased coins can now be ordered according to the name of the column that we want ... 
  #thank you Norker Play for your contribution ...
  #["Symbol", "Volume", "Bought At", "Now At", "TP %", "SL %", "Change %", "Profit $", "Time Held"]
  SORT_TABLE_BY: "Change %"
  REVERSE_SORT: False
  
  #I will no longer ask if you want to continue a new session, I would simply start from 0
  ALWAYS_OVERWRITE: False

 #Enables the use of currencies with greater or lesser volume
  USE_MOST_VOLUME_COINS: True
  #idea from my psychologist, thanks Sebastian V.
  #Two different currencies can be used as a range (within the market table in Binance ordered from highest to lowest)
  COINS_MAX_VOLUME: BTC #ETH   #5000000000
  COINS_MIN_VOLUME: DAR #STORJ #100000000
  
  SIGNALLING_MODULES:
    # NOTE: Only use the "os_xxxxxxxxx" or "nigec_xxxxxxxxx" etc signal/pause modules with this fork as 
    # the default ones WILL NOT work due to customisations for my specific purposes
    #
    - Ak_Scalp
    - custsignalmod
    #- djcommie_signalbuy_rsi_stoch
    #- djcommie_signalsell_rsi_stoch
    #- nigec_signalbuy_RSI
    #- nigec_signalsell_RSI
    #- os_pausebot_MA
    #- os_pausebot_MAOSC
    #- os_pausebot_MAv2
    #- VolScan
    #- the_snail_test
    #- the_snail_v2
    #- os_signalbuy_3SMA
    #- os_signalbuy_3SMAv2
    #- os_signalbuy_RECOMM
    #- os_signalsell_RECOMM
    #- os_signalsell_3SMA
    #- os_signalsell_3SMAv2
    #- os_signalbuy_RECOMM_SBUY
    #- pausebotmod
    #- rsi-mod
    #- webserver
    #- signalsample
    #- signalsamplemod